version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: ./mysite
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/mysite
    ports:
      - '8000:8000'

  worker_channels:
    build: ./mysite
    command: python manage.py runworker 
    volumes:
      - ./mysite:/mysite
    links:
      - redis

  channels:
    build: ./mysite
    command: daphne -b 0.0.0.0 -p 8001 mysite.asgi:application
    volumes:
      - ./mysite:/mysite
    ports:
      - '8001:8001'
    links:
      - redis

   
